# -----------------------------------------------------------------------------
# Configuration file for MantisBT utility scripts (YAML format)
#
# These default values can be overridden as needed from a 'config.yml'
# file, setting only those values that need to be set
# -----------------------------------------------------------------------------


# -----------------------------------------------------------------------------
# Github settings
#
github:
    # Personal access token
    # If null, connection to GitHub will be anonymous
    # Generate at https://github.com/settings/tokens
    # The token must have at least `public_repo` scope. Additionally,
    # - `write:org` is required to run github_plugin_teams.py
    # Note: Fine-grained tokens are currently not supported
    token: null

    # Global teams in mantisbt-plugins org that should have access to
    # all repositories.
    # key = team name, value = privilege (pull, push or admin)
    teams:
        Core team:         admin
        translatewiki.net: push
